from embeddings import search_index, get_embedding_model, retrieve_context_with_pages
from genai_client import ask_groq_from_client, ask_google_from_client
from typing import List


def answer_question_simple(index, docs: List[dict], query: str, k: int = 3) -> str:
    """Answer question using simple context retrieval without LLM.
    
    Args:
        index: FAISS index for similarity search
        docs: List of document chunks with metadata
        query: User's question
        k: Number of top results to retrieve
        
    Returns:
        Formatted answer with context excerpt
    """
    model = get_embedding_model()
    distances, indices = search_index(index, model, query, k=k)
    context = retrieve_context_with_pages(indices, docs)

    # simple formatted answer without LLM
    answer = f"Question:\n{query}\n\nContext excerpt:\n{context[:800]}"
    return answer


def edubot_with_groq(index, docs: List[dict], question: str, k: int = 3, api_key: str = None) -> str:
    """Answer question using Groq LLM with retrieved context.
    
    Args:
        index: FAISS index for similarity search
        docs: List of document chunks with metadata
        question: User's question
        k: Number of top results to retrieve
        api_key: Optional Groq API key
        
    Returns:
        Answer generated by Groq LLM
        
    Raises:
        RuntimeError: If Groq API key is not set or API call fails
    """
    from genai_client import get_groq_client
    try:
        client = get_groq_client(api_key=api_key)
    except RuntimeError as e:
        raise RuntimeError(f"Groq initialization failed: {str(e)}")
    
    model = get_embedding_model()
    distances, indices = search_index(index, model, question, k=k)
    context = retrieve_context_with_pages(indices, docs)
    return ask_groq_from_client(client, context, question)


def edubot_with_google(index, docs: List[dict], question: str, k: int = 3, api_key: str = None) -> str:
    """Answer question using Google GenAI LLM with retrieved context.
    
    Args:
        index: FAISS index for similarity search
        docs: List of document chunks with metadata
        question: User's question
        k: Number of top results to retrieve
        api_key: Optional Google GenAI API key
        
    Returns:
        Answer generated by Google GenAI
        
    Raises:
        RuntimeError: If Google GenAI API key is not set or API call fails
    """
    from genai_client import get_google_client
    try:
        client = get_google_client(api_key=api_key)
    except RuntimeError as e:
        raise RuntimeError(f"Google GenAI initialization failed: {str(e)}")
    
    model = get_embedding_model()
    distances, indices = search_index(index, model, question, k=k)
    context = retrieve_context_with_pages(indices, docs)
    return ask_google_from_client(client, context, question)
